const jCategory = [
    {
       index: 0, 
      image:"../images/google.png",
      title: "Software Engineer",
      rate: "$900-1200/m",
      av: "Full Time",
      companyName: "Google",
      location: "USA",
      vacancy: "01",
      hours: "40 hours/week",
      description: "We are looking for a Software Engineer to join our team. The ideal candidate will have  experience in developing scalable applications and a passion for technology.",
      workplace: "work from home",
      education: "Bachelor's degree in Computer Science or related field",
      experience: "2+ years of experience in software development",
    },
     {
       index: 1, 
      image:"../images/uber.png",
      title: "Freelance ",
      rate: "$900-1200/m",
      av: "Part Time",
       companyName: "Uber",
      location: "USA",
      vacancy: "04",
      hours: "40 hours/week",
      description: "We are looking for a Business Associate to join our team. The ideal candidate will have experience in business analysis and a passion for technology.",
      workplace: "work from office",
      education: "Bachelor's degree in Computer Science or related field",
      experience: "2+ years of experience in software development",
    },

     {
       index: 2, 
      image:"../images/apple.png",
      title: "Web Developer",
      rate: "$900-1200/m",
      av: "Part Time",
       companyName: "Apple",
      location: "USA",
      vacancy: "04",
      hours: "40 hours/week",
      description: "We are looking for a Business Associate to join our team. The ideal candidate will have experience in business analysis and a passion for technology.",
      workplace: "work from office",
      education: "Bachelor's degree in Computer Science or related field",
      experience: "2+ years of experience in software development",
    },
        {
        index: 3, 
        image:"../images/facebook.png",
        title: "Data Analyst",
        rate: "$900-1200/m",
        av: "Freelancer",
        companyName: "Facebook",
        location: "USA",
        vacancy: "02",
        hours: "40 hours/week",
        description: "We are looking for a Data Analyst to join our team. The ideal candidate will have experience in data analysis and a passion for technology.",
        workplace: "work from home",
        education: "Bachelor's degree in Computer Science or related field",
        experience: "2+ years of experience in software development",
        },
         {
       index: 4, 
      image:"../images/Instagram.png",
      title: "Product Designer",
      rate: "$900-1200/m",
      av: "Part Time",
       companyName: "Instagram",
      location: "USA",
      vacancy: "04",
      hours: "40 hours/week",
      description: "We are looking for a Business Associate to join our team. The ideal candidate will have experience in business analysis and a passion for technology.",
      workplace: "work from office",
      education: "Bachelor's degree in Computer Science or related field",
      experience: "2+ years of experience in software development",
    },
        {
        index: 5, 
        image:"../images/linkedin.png",
        title: "Business Associate",
        rate: "$900-1200/m",
        av: "Part Time",
        companyName: "LinkedIn",
        location: "USA",
        vacancy: "04",
        hours: "40 hours/week",
        description: "We are looking for a Business Associate to join our team. The ideal candidate will have experience in business analysis and a passion for technology.",
        workplace: "work from office",
        education: "Bachelor's degree in Computer Science or related field",
        experience: "2+ years of experience in software development",
        },
    
    
] 